# Generated by Django 4.2 on 2023-04-09 23:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="historicalproduct",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical Producto",
                "verbose_name_plural": "historical Productos",
            },
        ),
        migrations.AlterModelOptions(
            name="product",
            options={"verbose_name": "Producto", "verbose_name_plural": "Productos"},
        ),
        migrations.AlterField(
            model_name="categoryproduct",
            name="deleted",
            field=models.DateField(verbose_name="Fecha de eliminación"),
        ),
        migrations.AlterField(
            model_name="historicalcategoryproduct",
            name="deleted",
            field=models.DateField(verbose_name="Fecha de eliminación"),
        ),
        migrations.AlterField(
            model_name="historicalindicator",
            name="deleted",
            field=models.DateField(verbose_name="Fecha de eliminación"),
        ),
        migrations.AlterField(
            model_name="historicalmeasureunit",
            name="deleted",
            field=models.DateField(verbose_name="Fecha de eliminación"),
        ),
        migrations.AlterField(
            model_name="historicalproduct",
            name="deleted",
            field=models.DateField(verbose_name="Fecha de eliminación"),
        ),
        migrations.AlterField(
            model_name="indicator",
            name="deleted",
            field=models.DateField(verbose_name="Fecha de eliminación"),
        ),
        migrations.AlterField(
            model_name="measureunit",
            name="deleted",
            field=models.DateField(verbose_name="Fecha de eliminación"),
        ),
        migrations.AlterField(
            model_name="product",
            name="deleted",
            field=models.DateField(verbose_name="Fecha de eliminación"),
        ),
    ]
