# Generated by Django 4.2 on 2023-04-09 23:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0002_alter_historicalproduct_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="categoryproduct",
            name="measure_unit",
        ),
        migrations.RemoveField(
            model_name="historicalcategoryproduct",
            name="measure_unit",
        ),
        migrations.AddField(
            model_name="historicalproduct",
            name="measure_unit",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="products.measureunit",
                verbose_name="Unidad de medida",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="measure_unit",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="products.measureunit",
                verbose_name="Unidad de medida",
            ),
        ),
    ]
