# Generated by Django 4.2 on 2023-04-09 23:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0003_remove_categoryproduct_measure_unit_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalproduct",
            name="category",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="products.categoryproduct",
                verbose_name="Categoria",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="products.categoryproduct",
                verbose_name="Categoria",
            ),
            preserve_default=False,
        ),
    ]
