# Generated by Django 4.2 on 2023-04-09 23:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0004_historicalproduct_category_product_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="categoryproduct",
            name="deleted",
            field=models.DateField(
                blank=True, null=True, verbose_name="Fecha de eliminación"
            ),
        ),
        migrations.AlterField(
            model_name="historicalcategoryproduct",
            name="deleted",
            field=models.DateField(
                blank=True, null=True, verbose_name="Fecha de eliminación"
            ),
        ),
        migrations.AlterField(
            model_name="historicalindicator",
            name="deleted",
            field=models.DateField(
                blank=True, null=True, verbose_name="Fecha de eliminación"
            ),
        ),
        migrations.AlterField(
            model_name="historicalmeasureunit",
            name="deleted",
            field=models.DateField(
                blank=True, null=True, verbose_name="Fecha de eliminación"
            ),
        ),
        migrations.AlterField(
            model_name="historicalproduct",
            name="deleted",
            field=models.DateField(
                blank=True, null=True, verbose_name="Fecha de eliminación"
            ),
        ),
        migrations.AlterField(
            model_name="indicator",
            name="deleted",
            field=models.DateField(
                blank=True, null=True, verbose_name="Fecha de eliminación"
            ),
        ),
        migrations.AlterField(
            model_name="measureunit",
            name="deleted",
            field=models.DateField(
                blank=True, null=True, verbose_name="Fecha de eliminación"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="deleted",
            field=models.DateField(
                blank=True, null=True, verbose_name="Fecha de eliminación"
            ),
        ),
    ]
