# Generated by Django 4.2 on 2023-04-23 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0006_alter_categoryproduct_deleted_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalproduct",
            name="measure_unit",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="products.measureunit",
                verbose_name="Unidad de medida",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="measure_unit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="products.measureunit",
                verbose_name="Unidad de medida",
            ),
        ),
    ]
